name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    if: needs.workflow_config.outputs.do_release == 'true'
    
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg="OVERARCH_RELEASE=${{ github.event.ref }}" --tag overarch:${{ github.event.ref }}
